# SPDX-FileCopyrightText: 2025 Hannes Lindenblatt
#
# SPDX-License-Identifier: CC0-1.0

name: redcamel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - numpy>=1.2
  - numba>=0.58
  - matplotlib>=3.7
  - plopp>=25
  - scipp>=25
  - scipy>=1.10
  - graphviz>=0.20
  - ipywidgets>=8
  - pip
  - pip:
    - chemformula>=1.2
