# SPDX-FileCopyrightText: 2025 Hannes Lindenblatt
#
# SPDX-License-Identifier: CC0-1.0

name: redcamel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - numpy>=2.2.6
  - numba>=0.61.2
  - matplotlib>=3.10.3
  - plopp>=25.6.1
  - scipp>=25.5.1
  - scipy>=1.16.0
  - graphviz>=0.21
  - ipywidgets>=8.1.7
  - pip
  - pip:
    - chemformula>=1.3.1
