# SPDX-FileCopyrightText: 2025 Hannes Lindenblatt
#
# SPDX-License-Identifier: CC0-1.0

name: redcamel
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - numpy>=1.2
  - numba>=0.58
  - matplotlib-base>=3.7
  - plopp>=25
  - scipp>=25
  - scipy>=1.10
  - python-graphviz>=0.20
  - ipywidgets>=8
  - h5py>=3,<4
  - ipykernel>=6,<7
  - ipympl>=0.9,<0.10
  - pip
  - pip:
    - chemformula>=1.2
