# SPDX-FileCopyrightText: 2025 Hannes Lindenblatt
#
# SPDX-License-Identifier: CC0-1.0

name: remigui
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3
  - numpy
  - matplotlib
  - xarray
  - pip
  - pip:
    - chemformula
