# SPDX-FileCopyrightText: 2025 Hannes Lindenblatt
#
# SPDX-License-Identifier: CC0-1.0
[workspace]
name = "redcamel"
version = "0.1.8"
description = "GUI tool to simulate Reaction Microscope detector images."
readme = "README.md"
authors = [
    "Patrizia Schoch",
    "Hannes Lindenblatt <hannes.lindenblatt@desy.de>",
    "Magdalena Orlowska",
]
license = "GPL-3.0-or-later"
license-file = "LICENSES/GPL-3.0-or-later.txt"
homepage = "https://codeberg.org/FlashREMI/RedCamel"
repository = "https://codeberg.org/FlashREMI/RedCamel.git"

channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

[dependencies]
h5py = ">=3,<4"
ipywidgets = ">=8"
ipykernel = ">=6,<7"
ipympl = ">=0.9,<0.10"
matplotlib-base = ">=3.7"
numba = ">=0.65"
numpy = ">=1.2"
plopp = ">=25"
python = ">=3.11"
python-graphviz = ">=0.20"
scipp = ">=25"
scipy = ">=1.10"

[pypi-dependencies]
chemformula = ">=1.2"
redcamel = { path = ".", editable = true }

[tasks.redcamel]
description = "Launch the RedCamel GUI program"
cmd = "redcamel"

[environments]
jupyterlab = ["jupyterlab"]
test = ["test"]

[feature.jupyterlab.dependencies]
jupyterlab = "*"
pixi-kernel = "*"

[feature.jupyterlab.tasks.jupyterlab]
description = "Launch a local jupyter lab server for running the example notebooks."
cmd = "jupyter-lab"

[feature.test.dependencies]
pytest = ">=9,<10"
pytest-cov = ">=7,<8"
pytest-sugar = ">=1.1,<1.2"
ruff = ">=0.15,<0.16"
pre-commit = ">=4.5.1,<5"
reuse = ">=6.2,<7"

[feature.test.tasks.test]
description = "Run all python tests"
cmd = "pytest"
[feature.test.tasks.code_analysis]
description = "Run static code analyis with ruff"
cmd = ["ruff", "check", "src/**/*.py", "examples/*.ipynb", "test/**/*.py"]

[feature.test.tasks.autoformat_python]
description = "Apply automatic python formatting rules with ruff"
cmd = ["ruff", "format", "src/**/*.py", "examples/*.ipynb", "test/**/*.py"]

[feature.test.tasks.autoformat_markdown]
description = "Apply automatic markdown formatting rules with prettier"
cmd = ["npx", "prettier", "--write", "**/*.md"]

[feature.test.tasks.reuse_lint]
description = "Check licenses with reuse"
cmd = ["reuse", "lint"]

[feature.test.tasks.pre-commit]
description = "Run pre-commit hooks"
cmd = ["pre-commit", "run"]

[feature.test.tasks.all_checks]
description = "Run static code analysis, python formatter and markdown formatter."
depends-on = [
    {task = "code_analysis"},
    {task = "autoformat_python"},
    {task = "autoformat_markdown"},
    {task = "reuse_lint"},
]
