# SPDX-FileCopyrightText: 2025 Hannes Lindenblatt
#
# SPDX-License-Identifier: CC0-1.0
[project]
name = "redcamel"
version = "0.1.8"
description = "GUI tool to simulate Reaction Microscope detector images."
readme = "README.md"
authors = [
    {name = "Patrizia Schoch"},
    {name = "Hannes Lindenblatt", email = "hannes.lindenblatt@desy.de" },
    {name = "Magdalena Orlowska"},
]
maintainers = [
    {name = "Hannes Lindenblatt", email = "hannes.lindenblatt@desy.de" },
]
license = "GPL-3.0-or-later"
license-files = ["LICENSES/*", "REUSE.toml", "CITATION.cff"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Visualization",
]

requires-python = ">=3.11"
dependencies = [
    "chemformula>=1.2",
    "graphviz>=0.20",
    "h5py>=3,<4",
    "ipywidgets>=8",
    "ipympl>=0.9",
    "matplotlib>=3.7",
    "numba>=0.58",
    "numpy>=1.2",
    "plopp>=23",
    "scipp>=23",
    "scipy>=1.10",
]

[project.gui-scripts]
redcamel = "redcamel.remi_gui:main"

[project.urls]
Homepage = "https://codeberg.org/FlashREMI/RedCamel"
Repository = "https://codeberg.org/FlashREMI/RedCamel.git"

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
test = [
    "pytest>=9,<10",
    "pytest-cov>=7,<8",
    "pytest-sugar>=1.1,<1.2",
]
lint = [
    "ruff>=0.15,<0.16",
    "reuse>=6.2,<7"
]
dev = [
  {include-group = "lint"},
  {include-group = "test"}
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
    "PLC", # pylint-convention
    "PLE", # pylint-error
#    "PLR", # pylint-refactor #TODO keep in mind for refactoring later
    "PLW", # pylint-warning
]
isort.split-on-trailing-comma=false

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true
