# Basic CI setup: Lint with ruff, run tests with pytest
name: Test

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            lfs: true
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Ruff lint
        run: uv run ruff check .
      - name: Ruff format
        run: uv run ruff format --diff .
      - name: Prettier format
        run: npx prettier --check "**/*.md"
      - name: Setup imagemagick
        uses: mfinelli/setup-imagemagick@v6
      - name: Check images
        run: magick identify **/*.png

  test:
    needs: lint
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest] # not for now: , macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            lfs: true
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - run: sudo apt-get install -y python3-tk
      - name: Run pytest with coverage
        run: uv run pytest --cov=src --cov-report=term --cov-report=xml
      - name: Test package building
        run: uv build
