name: Pre-Release

on:
  release:
    types: [prereleased]

jobs:
  pypi:
    name: Test
    runs-on: ubuntu-latest
    # Environment and permissions trusted publishing.
    environment:
      # Create this environment in the GitHub repository under Settings -> Environments
      name: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
            lfs: true
      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
            enable-cache: "auto"
            cache-python: "true"
      - name: Run tests
        run: uv run --group test pytest
      - name: Build package
        run: uv build
      # Stop here as it is a release draft!
